# Generated by Django 5.2.3 on 2025-08-30 08:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('api', '0001_initial'), ('api', '0002_remove_announcement_title_and_more'), ('api', '0003_remove_created_by_from_announcements'), ('api', '0004_auto_20250830_0801'), ('api', '0005_officer_email_officer_linkedin_url_officer_name_and_more')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'highlights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clerk_user_id', models.TextField(help_text='Unique ID from Clerk auth', unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('role', models.CharField(help_text="Display role e.g. 'President', 'VP of Events'", max_length=100)),
                ('is_officer', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('event_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to='api.user')),
            ],
            options={
                'db_table': 'events',
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='EventRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=150)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='api.event')),
            ],
            options={
                'db_table': 'event_rsvps',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('event', 'email'), name='unique_event_email_rsvp')],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('discord_message_id', models.CharField(blank=True, max_length=64, null=True)),
                ('display_text', models.CharField(blank=True, max_length=200, null=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(help_text="e.g. 'VP of Tech', 'Treasurer'", max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('order_index', models.IntegerField(default=0, help_text='Used to control ordering on frontend')),
                ('user', models.OneToOneField(blank=True, db_column='user_id', help_text='Optional link to user account - null for standalone officers', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='officer_profile', to='api.user')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('name', models.CharField(default='Officer', help_text='Display name for the officer', max_length=150)),
            ],
            options={
                'db_table': 'officers',
                'ordering': ['order_index', 'position'],
            },
        ),
    ]
