# Generated by Django 5.2.3 on 2025-09-02 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_officer_image_url'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS highlights;",
            reverse_sql="CREATE TABLE highlights (id SERIAL PRIMARY KEY, title VARCHAR(200) NOT NULL, description TEXT, image_url VARCHAR(200), link VARCHAR(200), created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW());"
        ),
    ]
