# Generated by Django 5.2.3 on 2025-08-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="title",
        ),
        migrations.AddField(
            model_name="announcement",
            name="discord_message_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="display_text",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="is_draft",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
