# Generated by Django 5.2.3 on 2025-08-29 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_announcement_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='created_by',
        ),
    ]
