# Generated by Django 5.2.3 on 2025-08-30 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_created_by_from_announcements'),
    ]

    operations = [
    ]
