# Generated by Django 5.2.3 on 2025-08-30 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20250830_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='name',
            field=models.CharField(default='Officer', help_text='Display name for the officer', max_length=150),
        ),
        migrations.AlterField(
            model_name='officer',
            name='user',
            field=models.OneToOneField(blank=True, db_column='user_id', help_text='Optional link to user account - null for standalone officers', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='officer_profile', to='api.user'),
        ),
    ]
