# Generated by Django 5.2.3 on 2025-08-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial_squashed_0005_officer_email_officer_linkedin_url_officer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='image_url',
            field=models.TextField(blank=True, help_text='Image URL or base64 data', null=True),
        ),
    ]
